
functions:
  index:
    handler: index.handler
    events:
      - http:
          method: get
layers:
  eggLayer:
    path: 'npm:@midwayjs/egg-layer@beta'
package:
  include:
    - app/**
    - config/**
    - app.js
    - agent.js
    - index.js
  artifact: midwayFaas.zip
plugins:
  - serverless-midway-plugin
provider:
  name: aliyun
service:
  name: serverless-midway-faas
